default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= ENV['db_user'] %>
  password: <%= ENV['db_password'] %>

development:
  <<: *default
  database: meal_planner_development

test:
  <<: *default
  database: meal_planner_test

production:
  <<: *default
  database: meal_planner_production
